Update JenkinsfileDeploy

diff --git a/JenkinsfileDeploy b/JenkinsfileDeploy
--- a/JenkinsfileDeploy
+++ b/JenkinsfileDeploy
@@ -37,7 +37,7 @@ pipeline {
                 '''
             }
         }
-        
+
         stage('Check OS and Apache Errors') {
             steps {
                 sh '''
@@ -49,17 +49,18 @@ pipeline {
 
                     if [ -f "$LOG_FILE" ]; then
                       echo "4xx Errors:"
-                      grep "400" $LOG_FILE || echo "No errors"
+                      grep " 4[0-9][0-9] " $LOG_FILE || echo "No 4xx errors"
 
                       echo "5xx Errors:"
-                      grep "500" $LOG_FILE || echo "No errors"
+                      grep " 5[0-9][0-9] " $LOG_FILE || echo "No 5xx errors"
                     else
                       echo "Apache log not found: $LOG_FILE"
                     fi
                 '''
             }
         }
-    }
+
+    } // <- closing stages block
 
     post {
         success {
